framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    php_errors:
        log: true
    http_client:
        scoped_clients:
            sms.notifications:
                base_uri: '%env(resolve:SMS_NOTIFICATION_URI%'
                headers:
                    name: 'X-API-KEY'
                    value: '%env(resolve:SMS_NOTIFICATION_API_KEY)%'
