framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'comanpatricia27@gmail.com'
        headers:
            From: 'Coman Patricia <comanpatricia27@gmail.com>'