framework:
    messenger:
        transports:
            mail_async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: mail_queue
            sms_async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: sms_queue
        routing:
            App\Message\SmsNotification: sms_async
            App\Mailer\NewsletterNotification: mail_async
