security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN: [ ROLE_TRAINER ]
        ROLE_TRAINER: [ ROLE_USER ]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        app_token_provider:
            entity:
                class: App\Entity\User
                property: token
        all_users:
            chain:
                providers: [ 'app_user_provider', 'app_token_provider' ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin/
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                enable_csrf: true
            logout:
                path: admin_logout
                target: admin_login
        main:
            lazy: true
            provider: all_users
            stateless: true
            json_login:
                check_path: api_login
                username_path: email
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator

    access_control:
     - { path: ^api/users/newsletter, roles: ROLE_ADMIN }
     - { path: ^/api/login, roles: PUBLIC_ACCESS }
     - { path: ^/api/users/register, roles: PUBLIC_ACCESS }
     - { path: ^api/users, roles: ROLE_ADMIN }
     - { path: ^api/admin, roles: ROLE_ADMIN }
     - { path: ^api/admin/dashboard, roles: ROLE_ADMIN }
     - { path: ^api/trainer, roles: ROLE_TRAINER }
     - { path: ^/reset/password }
