parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $programmeMinTimeInMinutes: '%env(PROGRAMME_MIN_TIME_IN_MINUTES)%'
            $programmeMaxTimeInMinutes: '%env(PROGRAMME_MAX_TIME_IN_MINUTES)%'
            $defaultPerPage: '%env(DEFAULT_PER_PAGE)%'
            $apiVersion: '%env(API_VERSION)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Message/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ "controller.service_arguments" ]

    App\EventListener\CustomResponseHeaderSubscriber:
        tags:
            - { name: doctrine.event_listener, event: onKernelResponse }
