<?php

namespace App\Validator;

use Symfony\Component\Validator\Constraint;

class Password extends Constraint
{
    public $message = "The password must contains at least 8 characters including an uppercase character & a special character";

    public function validatedBy()
    {
        return parent::validatedBy(); // TODO: Change the autogenerated stub
    }
}